import type { Metadata } from "next";
import "./globals.css";
import BackButton from "@/components/BackButton";
import DynamicMap from "@/components/DynamicMap";
import { trails } from "@/data/trail-markers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const stops = [
    "2:30 登山口",
    "3:13 七卡",
    "05:02 雪東",
    "05:55 三六九營地",
    "09:30 雪山主峰",
    "10:30 三六九營地",
    "11:37 雪山東峰",
    "13:05 登山口",
  ];
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="flex flex-col h-screen overflow-hidden bg-chang">
          <nav className="w-full p-4 flex items-center justify-center sticky top-0 z-10">
            <BackButton />
            <h1 className="text-xl font-bold">Hiking Journal</h1>
          </nav>

          <div className="flex flex-col md:flex-row flex-grow overflow-hidden">
            {/* 左邊：會換的內容 */}
            <div className="w-full md:basis-[60%] max-w-3xl overflow-y-auto p-6 pt-0 mx-auto">
              {children}
            </div>

            {/* 右邊：永遠存在，不會重刷 */}
            <div className="hidden md:block basis-[40%] sticky top-0 h-screen">
              <DynamicMap
                center={[24.383401, 121.231754]}
                zoom={15}
                markers={trails}
              />
              <div className="mt-5">
                {stops.map((stop, idx) => (
                  <div
                    key={idx}
                    className="relative p-2 m-1 font-medium bg-black text-white rounded-md text-sm w-fit"
                  >
                    {stop}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
